region = "us-east-1"
customer_name = "Zabihullah"
project       = "portfolio"
repository_url = "https://github.com/Zabihkeraam1/project-template.git"
branch = "master"
db_password = "your_secure_password"
db_username = "postgres"
db_name = "myDatabase"